import type { GameCommand, JsonObject } from "./contracts.ts";

export interface Card { rank: string; suit: string }
export interface PokerRuntime { remainingDeck: Card[]; holeCardsByPlayer: Record<string, Card[]> }
export interface Transition { publicState: JsonObject; privateState: JsonObject; deadlineAt: string | null }
type P = Record<string, any>; type S = JsonObject & Record<string, any>;
const SB=5, SHOW=10, SUMMARY=14, suits=["♥","♦","♣","♠"], ranks=["2","3","4","5","6","7","8","9","10","J","Q","K","A"];
const cp=<T>(x:T):T=>structuredClone(x), n=(x:any,d=0)=>Number.isSafeInteger(x)?x:d, on=(x:any)=>x===true;
const tag=(x:string)=>({[x]:{}}), kind=(x:any)=>typeof x==="string"?x:x&&typeof x==="object"&&!Array.isArray(x)?Object.keys(x)[0]??"":"";
const ps=(s:S):P[]=>(s.players??=[]), fail=(x:string):never=>{throw new Error(x)}, br=(s:S)=>Math.max(n(s.smallBlind,SB),1)*2;
const rt=(x:JsonObject):PokerRuntime=>({remainingDeck:Array.isArray(x.remainingDeck)?x.remainingDeck as unknown as Card[]:[],holeCardsByPlayer:x.holeCardsByPlayer&&typeof x.holeCardsByPlayer==="object"&&!Array.isArray(x.holeCardsByPlayer)?x.holeCardsByPlayer as unknown as Record<string,Card[]>:{}});
const eligible=(p:P)=>!on(p.isEliminated)&&!on(p.isSittingOut)&&n(p.stack)>0, inHand=(p:P)=>!on(p.isEliminated)&&!on(p.isFolded), live=(p:P)=>eligible(p)&&!on(p.isFolded);
const value=(c:Card)=>ranks.indexOf(c.rank)+2, handNames=["High Card","Pair","2 Pair","3 of a Kind","Straight","Flush","Full House","4 of a Kind","Straight Flush","Royal Flush"];

/** Server entropy only; no request may provide cards, deck order, or a seed. */
export function cryptoDeck():Card[]{const d=suits.flatMap(s=>ranks.map(rank=>({rank,suit:s})));for(let i=d.length-1;i;i--){let x:number,lim=Math.floor(4294967296/(i+1))*(i+1);do{x=crypto.getRandomValues(new Uint32Array(1))[0]}while(x>=lim);const j=x%(i+1);[d[i],d[j]]=[d[j],d[i]]}return d}
/** Pure test hook. It is deliberately not used by the HTTP dispatcher. */
export function applyCommandWithDeck(a:JsonObject,b:JsonObject,id:string,c:GameCommand,deck:Card[]):Transition{return go(a,b,id,c,()=>cp(deck))}
export function applyCommand(a:JsonObject,b:JsonObject,id:string,c:GameCommand):Transition{return go(a,b,id,c,cryptoDeck)}
function go(pub:JsonObject,priv:JsonObject,id:string,c:GameCommand,f:()=>Card[]):Transition{const s=cp(pub)as S,r=rt(cp(priv)as JsonObject),found=ps(s).find(x=>x.id===id);if(!found)fail("not_room_member");const p=found as P;switch(c.kind){case"setReady":if(!["waiting","handSummary"].includes(kind(s.phase))||!eligible(p))fail("actor_ineligible");p.isReady=c.ready;break;case"startGame":start(s,r,id,f);break;case"bet":action(s,r,id,c.betKind,c.amount);break;case"showCards":show(s,r,id);break;case"advanceSummary":if(kind(s.phase)!=="showdown"||s.pendingRevealPlayerID)fail("reveal_incomplete");finish(s);break;case"startNextHand":next(s,r,id,f);break;case"setSittingOut":sit(s,r,id,c.sittingOut);break;case"updateSettings":settings(s,id,c.startingStack,c.smallBlind);break;case"raiseBlinds":if(kind(s.phase)!=="handSummary"||s.hostID&&s.hostID!==id||!Number.isSafeInteger(c.smallBlind)||c.smallBlind<=n(s.smallBlind,SB))fail("illegal_blind_change");s.smallBlind=c.smallBlind;s.blindIncreaseAnnouncement={id:crypto.randomUUID(),smallBlind:c.smallBlind};break;case"endGame":end(s,id,c.reason);break;case"resetRoom":reset(s,r,id);break}ui(s);return{publicState:s,privateState:r as unknown as JsonObject,deadlineAt:deadline(s)}}
/** Function callers invoke this before reads and commands. */
export function applyExpiredDeadline(pub:JsonObject,priv:JsonObject,at:string|null,now=new Date()):Transition|null{const time=at?Date.parse(at):NaN;if(!Number.isFinite(time)||time>now.getTime())return null;const s=cp(pub)as S,r=rt(cp(priv)as JsonObject);if(kind(s.phase)!=="showdown")return null;if(s.pendingRevealPlayerID)show(s,r,s.pendingRevealPlayerID);else finish(s);ui(s);return{publicState:s,privateState:r as unknown as JsonObject,deadlineAt:deadline(s)}}
function dealer(s:S){return Math.max(0,ps(s).findIndex(p=>on(p.isDealer)))}function scan(s:S,from:number,fn:(p:P)=>boolean,inc=false){for(let o=inc?0:1;o<ps(s).length;o++){const i=(from+o)%ps(s).length;if(fn(ps(s)[i]))return i}return null}
function settings(s:S,id:string,stack:number,smallBlind:number){if(kind(s.phase)!=="waiting"||s.hostID&&s.hostID!==id||!Number.isSafeInteger(stack)||stack<100||stack>100000||!Number.isSafeInteger(smallBlind)||smallBlind<1||smallBlind>5000||stack<smallBlind*40)fail("illegal_settings_change");s.startingStack=stack;s.smallBlind=smallBlind;ps(s).forEach(p=>{p.stack=stack;p.isReady=false})}
function blinds(s:S):[number,number]|null{const a=ps(s).filter(eligible),d=dealer(s);if(a.length<2)return null;const x=a.length===2?d:scan(s,d,eligible),y=x===null?null:scan(s,x,eligible);return x===null||y===null?null:[x,y]}
function post(s:S,i:number,x:number){const p=ps(s)[i],v=Math.min(Math.max(0,x),n(p.stack));if(!v)return;p.stack=n(p.stack)-v;p.currentBet=n(p.currentBet)+v;s.pot=n(s.pot)+v;const c=s.contributions??={};c[p.id]=n(c[p.id])+v;s.streetBetLevel=Math.max(n(s.streetBetLevel),n(p.currentBet))}
function mark(s:S,id:string){const a=s.actedThisStreet??=[];if(!a.includes(id))a.push(id)}function allin(s:S){ps(s).filter(p=>inHand(p)&&n(p.stack)===0).forEach(p=>mark(s,p.id))}
function clear(s:S){ps(s).forEach(p=>p.currentBet=0);s.streetBetLevel=0;s.actedThisStreet=[];s.activePlayerID=null}
function first(s:S,pre:boolean){const b=blinds(s),a=ps(s).filter(eligible).length,d=dealer(s),start=pre&&b?(a===2?b[0]:(b[1]+1)%ps(s).length):(d+1)%ps(s).length,i=scan(s,start,live,true);s.activePlayerID=i===null?null:ps(s)[i].id}
function rotate(s:S){const old=ps(s).findIndex(p=>on(p.isDealer));if(old>=0){ps(s)[old].isDealer=false;const i=scan(s,old,eligible);if(i!==null)ps(s)[i].isDealer=true}else{const i=ps(s).findIndex(eligible);if(i>=0)ps(s)[i].isDealer=true}}
function start(s:S,r:PokerRuntime,id:string,f:()=>Card[]){if(!["waiting","handSummary"].includes(kind(s.phase)))fail("illegal_phase");if(s.hostID&&s.hostID!==id)fail("not_host");const a=ps(s).filter(eligible);if(!a.length||!a.every(p=>on(p.isReady)))fail("not_all_ready");if(a.length<2&&ps(s).some(p=>on(p.isSittingOut)))fail("insufficient_players");ps(s).forEach(p=>{p.isFolded=false;p.currentBet=0;const h=(s.handStats??={})[p.id]??={handsWon:0,handsPlayed:0,biggestPot:0};if(eligible(p))h.handsPlayed=n(h.handsPlayed)+1});s.board=[null,null,null,null,null];s.handID=crypto.randomUUID();s.pot=0;s.streetBetLevel=0;s.lastRaiseSize=br(s);s.actedThisStreet=[];s.contributions={};s.handResult=null;s.lastAggressorID=null;s.pendingRevealPlayerID=null;s.bettingRound=tag("preFlop");s.phase=tag("playing");rotate(s);r.remainingDeck=f();r.holeCardsByPlayer={};ps(s).filter(eligible).forEach(p=>r.holeCardsByPlayer[p.id]=[draw(r),draw(r)].filter(Boolean)as Card[]);const b=blinds(s);if(b){post(s,b[0],Math.min(n(s.smallBlind,SB),n(ps(s)[b[0]].stack)));post(s,b[1],Math.min(br(s),n(ps(s)[b[1]].stack)));allin(s)}first(s,true);if(!s.activePlayerID)resolve(s,r)}
function draw(r:PokerRuntime){return r.remainingDeck.shift()??null}function round(s:S){return kind(s.bettingRound)}
function cap(s:S,id:string){const me=ps(s).find(p=>p.id===id)!,own=n(me.currentBet)+n(me.stack),v=ps(s).filter(p=>p.id!==id&&!on(p.isFolded)&&!on(p.isEliminated)).map(p=>n(p.currentBet)+n(p.stack));return v.length?Math.min(own,Math.max(...v)):own}
function done(s:S){const a=ps(s).filter(inHand);if(a.length<=1||ps(s).filter(eligible).length===1)return true;const actors=a.filter(live),set=new Set(s.actedThisStreet??[]),level=n(s.streetBetLevel);return !actors.length||actors.every(p=>n(p.currentBet)>=level&&set.has(p.id))}
function action(s:S,r:PokerRuntime,id:string,k:string,amount?:number){if(kind(s.phase)!=="playing"||s.activePlayerID!==id)fail("not_your_turn");const i=ps(s).findIndex(p=>p.id===id),p=ps(s)[i],level=n(s.streetBetLevel),cur=n(p.currentBet);if(!live(p))fail("actor_ineligible");if(k==="fold")p.isFolded=true;else if(k==="check"){if(cur!==level)fail("illegal_check")}else if(k==="call"){const owed=Math.min(level-cur,n(p.stack));if(level<=cur||owed<=0||!Number.isSafeInteger(amount)||amount!<owed)fail("illegal_call");post(s,i,owed)}else if(k==="raise"){if(!Number.isSafeInteger(amount)||amount!<=level||amount!>cap(s,id))fail("illegal_raise");const need=amount!-cur,min=level+Math.max(n(s.lastRaiseSize,br(s)),br(s)),all=cur+n(p.stack);if(need<=0||need>n(p.stack)||(amount!<min&&amount!==all))fail("illegal_raise");post(s,i,need);if(amount!-level>=Math.max(n(s.lastRaiseSize,br(s)),br(s))){s.lastRaiseSize=amount!-level;s.lastAggressorID=id;s.actedThisStreet=[id];allin(s)}}else fail("illegal_bet");mark(s,id);if(ps(s).filter(inHand).length===1&&ps(s).filter(p=>!on(p.isEliminated)&&!on(p.isSittingOut)).length>1){award(s,r,false);return}if(done(s))resolve(s,r);else{const q=scan(s,i,live);s.activePlayerID=q===null?null:ps(s)[q].id;if(!s.activePlayerID&&!ps(s).some(live))resolve(s,r)}}
function resolve(s:S,r:PokerRuntime){if(round(s)==="river"){uncalled(s);award(s,r,true);return}uncalled(s);clear(s);allin(s);draw(r);if(round(s)==="preFlop"){s.board.splice(0,3,draw(r),draw(r),draw(r));s.bettingRound=tag("flop")}else if(round(s)==="flop"){s.board[3]=draw(r);s.bettingRound=tag("turn")}else{s.board[4]=draw(r);s.bettingRound=tag("river")}first(s,false);if(!ps(s).some(live))resolve(s,r)}
function uncalled(s:S){const c=s.contributions??={},a=Object.entries(c).filter(([,v])=>n(v)>0).sort((x,y)=>n(y[1])-n(x[1]));if(a.length<2)return;const back=n(a[0][1])-n(a[1][1]),p=ps(s).find(p=>p.id===a[0][0]);if(!back||!p)return;p.stack=n(p.stack)+back;p.currentBet=Math.max(0,n(p.currentBet)-back);s.pot=Math.max(0,n(s.pot)-back);c[p.id]=n(c[p.id])-back}
function cmp(a:number[],b:number[]){for(let i=0;i<Math.max(a.length,b.length);i++)if((a[i]??0)!==(b[i]??0))return(a[i]??0)>(b[i]??0)?1:-1;return 0}
function five(cs:Card[]){const v=cs.map(value).sort((a,b)=>b-a),m=new Map<number,number>();v.forEach(x=>m.set(x,(m.get(x)??0)+1));const g=[...m.entries()].sort((a,b)=>b[1]-a[1]||b[0]-a[0]),u=[...new Set(v)].sort((a,b)=>b-a),flush=cs.length===5&&new Set(cs.map(x=>x.suit)).size===1;let st=0;if(cs.length===5){if([14,5,4,3,2].every(x=>u.includes(x)))st=5;else for(let i=0;i<=u.length-5;i++)if(u[i]-u[i+4]===4){st=u[i];break}}if(flush&&st)return[st===14&&v.includes(10)?9:8,st];const q=g.find(x=>x[1]===4);if(q)return[7,q[0],v.find(x=>x!==q[0])??0];const t=g.find(x=>x[1]===3),p=g.find(x=>x[1]===2&&x[0]!==t?.[0]);if(t&&p)return[6,t[0],p[0]];if(flush)return[5,...v];if(st)return[4,st];if(t)return[3,t[0],...v.filter(x=>x!==t[0])];const pairs=g.filter(x=>x[1]===2);if(pairs.length>1)return[2,pairs[0][0],pairs[1][0],v.find(x=>x!==pairs[0][0]&&x!==pairs[1][0])??0];if(pairs[0])return[1,pairs[0][0],...v.filter(x=>x!==pairs[0][0])];return[0,...v]}
function score(c:Card[]){if(c.length<=5)return five(c);let best=[0];for(let a=0;a<c.length-4;a++)for(let b=a+1;b<c.length-3;b++)for(let d=b+1;d<c.length-2;d++)for(let e=d+1;e<c.length-1;e++)for(let f=e+1;f<c.length;f++){const x=five([c[a],c[b],c[d],c[e],c[f]]);if(cmp(x,best)>0)best=x}return best}
function layers(s:S){const c=s.contributions??={},levels=[...new Set(Object.values(c).map(x=>n(x)).filter(x=>x>0))].sort((a,b)=>a-b),out:any[]=[];let old=0;for(const l of levels){const ids=Object.keys(c).filter(id=>n(c[id])>=l),e=ids.filter(id=>{const p=ps(s).find(x=>x.id===id);return p&&inHand(p)}),x=(l-old)*ids.length;old=l;if(!x)continue;const last=out.at(-1);if(last&&last.eligibleIDs.length===e.length&&last.eligibleIDs.every((z:string)=>e.includes(z)))last.amount+=x;else out.push({amount:x,eligibleIDs:e,winnerIDs:[],shares:{},isSidePot:out.length>0})}return out}
function clockwise(s:S,ids:string[]){const q=new Set(ids),out:string[]=[],start=(dealer(s)+1)%ps(s).length;for(let i=0;i<ps(s).length;i++){const id=ps(s)[(start+i)%ps(s).length].id;if(q.has(id))out.push(id)}return out}
function credit(s:S,x:Record<string,number>){for(const[id,v]of Object.entries(x)){const p=ps(s).find(p=>p.id===id);if(p)p.stack=n(p.stack)+v;const h=(s.handStats??={})[id]??={handsWon:0,handsPlayed:0,biggestPot:0};h.handsWon=n(h.handsWon)+1;h.biggestPot=Math.max(n(h.biggestPot),v)}}function bust(s:S){ps(s).forEach(p=>{if(n(p.stack)<=0){p.stack=0;p.isEliminated=true}})}
function award(s:S,r:PokerRuntime,showdown:boolean){uncalled(s);const payout:Record<string,number>={},aw:any[]=[];for(const pot of layers(s)){let e:string[]=pot.eligibleIDs.filter((id:string)=>{const p=ps(s).find(x=>x.id===id);return p&&inHand(p)});if(!e.length)e=ps(s).filter(inHand).map(p=>p.id);if(!e.length)continue;let w:string[]=e;if(showdown&&e.length>1){let best:number[]|null=null;w=[];for(const id of e){const x=score([...(r.holeCardsByPlayer[id]??[]),...s.board.filter(Boolean)]);if(!best||cmp(x,best)>0){best=x;w=[id]}else if(cmp(x,best)===0)w.push(id)}}const sh:Record<string,number>={};w.forEach(id=>sh[id]=Math.floor(pot.amount/w.length));let rem=pot.amount%w.length;for(const id of clockwise(s,w)){if(!rem)break;sh[id]++;rem--}for(const[id,v]of Object.entries(sh))payout[id]=(payout[id]??0)+v;aw.push({...pot,winnerIDs:w,shares:sh})}if(showdown){s.handResult={pots:aw,payouts:payout,reveals:[],wentToShowdown:true,payoutsApplied:false};clear(s);s.phase=tag("showdown");begin(s);return}credit(s,payout);s.handResult={pots:aw,payouts:payout,reveals:[],wentToShowdown:false,payoutsApplied:true};s.pot=0;clear(s);bust(s);summaryState(s)}
function revealOrder(s:S){const ids=ps(s).filter(inHand).map(p=>p.id),start=typeof s.lastAggressorID==="string"&&ids.includes(s.lastAggressorID)?s.lastAggressorID:clockwise(s,ids)[0],i=ps(s).findIndex(p=>p.id===start);return i<0?[]:[...ps(s).slice(i),...ps(s).slice(0,i)].filter(p=>ids.includes(p.id)).map(p=>p.id)}
function begin(s:S){const shown=new Set((s.handResult.reveals??[]).map((x:any)=>x.playerID));s.pendingRevealPlayerID=revealOrder(s).find(id=>!shown.has(id))??null;s.activePlayerID=s.pendingRevealPlayerID}
function bestCards(c:Card[],want:number[]){if(c.length<=5)return c;for(let a=0;a<c.length-4;a++)for(let b=a+1;b<c.length-3;b++)for(let d=b+1;d<c.length-2;d++)for(let e=d+1;e<c.length-1;e++)for(let f=e+1;f<c.length;f++){const x=[c[a],c[b],c[d],c[e],c[f]];if(cmp(five(x),want)===0)return x}return c.slice(0,5)}
function show(s:S,r:PokerRuntime,id:string){if(kind(s.phase)!=="showdown"||s.pendingRevealPlayerID!==id)fail("not_your_reveal");const h=r.holeCardsByPlayer[id];if(!h?.length)fail("missing_hole_cards");const cards=[...h,...s.board.filter(Boolean)],x=score(cards);s.handResult.reveals.push({playerID:id,holeCards:h,rank:handNames[x[0]],bestFive:bestCards(cards,x)});begin(s)}
function summaryState(s:S){s.completedHandCount=n(s.completedHandCount)+1;ps(s).forEach(p=>p.isReady=false);s.endStats=ps(s).map(p=>{const h=(s.handStats??{})[p.id]??{};return{id:p.id,name:p.name,avatarIndex:n(p.avatarIndex),handsWon:n(h.handsWon),handsPlayed:n(h.handsPlayed),biggestPot:n(h.biggestPot),finalStack:n(p.stack),isWinner:(s.handResult?.pots??[]).some((x:any)=>x.winnerIDs.includes(p.id))}}).sort((a:any,b:any)=>b.finalStack-a.finalStack);s.phase=tag("handSummary");s.activePlayerID=null;s.pendingRevealPlayerID=null}
function finish(s:S){if(s.handResult&&!s.handResult.payoutsApplied){credit(s,s.handResult.payouts);s.handResult.payoutsApplied=true;s.pot=0}bust(s);summaryState(s)}
function next(s:S,r:PokerRuntime,id:string,f:()=>Card[]){if(kind(s.phase)!=="handSummary")fail("illegal_phase");if(s.hostID&&s.hostID!==id)fail("not_host");if(ps(s).filter(p=>!on(p.isEliminated)&&n(p.stack)>0).length<=1){end(s,id,"autoLastStanding");return}const a=ps(s).filter(eligible);if(a.length<2||!a.every(p=>on(p.isReady)))fail("not_all_ready");start(s,r,id,f)}
function sit(s:S,r:PokerRuntime,id:string,v:boolean){const p=ps(s).find(p=>p.id===id)!;if(on(p.isEliminated))fail("actor_ineligible");if(!v&&!['waiting','handSummary'].includes(kind(s.phase)))fail("illegal_phase");if(v&&kind(s.phase)==="playing"&&!on(p.isFolded)){if(s.activePlayerID===id)action(s,r,id,"fold");else{p.isFolded=true;if(ps(s).filter(live).length===1)award(s,r,false)}}p.isSittingOut=v;p.isReady=false}
function end(s:S,id:string,reason:string){if(kind(s.phase)!=="handSummary"||s.hostID&&s.hostID!==id)fail("illegal_phase");const a=ps(s).filter(p=>!on(p.isEliminated)&&n(p.stack)>0),top=Math.max(0,...a.map(p=>n(p.stack)),),w=a.filter(p=>n(p.stack)===top);if(reason==="manualFinish"&&w.length>1&&n(s.manualFinishTieAttempts)===0){s.manualFinishTieAttempts=1;fail("manual_finish_tied")}const win=reason==="manualFinishTieForfeit"?null:w.length===1?w[0].id:null;s.endStats=ps(s).map(p=>({id:p.id,name:p.name,avatarIndex:n(p.avatarIndex),handsWon:n((s.handStats??{})[p.id]?.handsWon),handsPlayed:n((s.handStats??{})[p.id]?.handsPlayed),biggestPot:n((s.handStats??{})[p.id]?.biggestPot),finalStack:n(p.stack),isWinner:p.id===win})).sort((a:any,b:any)=>b.finalStack-a.finalStack);s.phase=tag("ended");s.activePlayerID=null}
function reset(s:S,r:PokerRuntime,id:string){if(s.hostID&&s.hostID!==id)fail("not_host");s.phase=tag("waiting");s.handID=null;s.board=[null,null,null,null,null];s.pot=0;s.activePlayerID=null;s.pendingRevealPlayerID=null;s.handResult=null;s.contributions={};ps(s).forEach(p=>{p.isReady=false;p.isFolded=false;p.currentBet=0});r.remainingDeck=[];r.holeCardsByPlayer={}}
function ui(s:S){const p=ps(s).find(p=>p.id===s.heroID);s.callAmount=p?Math.max(0,n(s.streetBetLevel)-n(p.currentBet)):0;const min=n(s.streetBetLevel)+Math.max(n(s.lastRaiseSize,br(s)),br(s));s.raiseAmount=p?Math.min(min,cap(s,p.id)):min}
function deadline(s:S){return kind(s.phase)!=="showdown"?null:new Date(Date.now()+1000*(s.pendingRevealPlayerID?SHOW:SUMMARY)).toISOString()}
